export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_APPOINTMENTS_STATE_CHANGE = 'USER_APPOINTMENTS_STATE_CHANGE'

export const BARBER_STATE_CHANGE = 'BARBER_STATE_CHANGE'

export const CLEAR_DATA = 'CLEAR_DATA'
